language: android
dist: trusty
android:
  components:
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
licenses:
- android-sdk-license-.+
addons:
  sonarcloud:
    organization: grigory-rylov-github
    token:
      secure: BBJ2qN2gD20uE2L1tKTKJaYa6yAFgOagM93edhBVaYG/zEnIBEYMOwi8W1/UlrTYOtHk5Iu9zznQLWaRZDdlsVuNPdWrh6BXGZIgRzN1PxGRwnL1Yjqjf5Zn63p5SjU0HnsIPTv8DgrG8vqcj6jX15paaZBbo0vXDwumpdH6UgPrvo349m0Z+sNSbr9Aw4GDhLCqoOLUBEiHaHvgngjTYTyQtNwDI4JQBpdXdn4mAeQWVsmr4ucXh87hnWlRBhTLnMy9X8f0BnWgy9rYh6S9nja90u1Y+q96+eB71r7uBC/rmePTKU2gikAkqNp5MOqoY1bH7RjWu2+1udl0NpAc3HpCSGadL2g3FbAUF35Th9gVpiCivEZl7+g2ynLo8jEURVA/39ODonbj/my1nU7ntXGj3nxrLhii2nngLy3blFkwdjBkyq60KgLU9xV3ROwCEPkfJk3VglClB0lj9fE2gKpz6Yft4sTWEa9CJT6jtTjAl8eGcxOO7h7ltZfSDeZRX9I4eJvMrwaWhIzliCck2+a34boWeTlaTa/L5AVsfmIxxIWtIrS2j7HvtsW5JbJ2uOKNs1jwWxo9r4PvlIXoLR/5RBlC9OrsIvAHPFAzS9vV1D4HQiq/BtPaTJqzA0NT+MsbBTyanWLh4pGyjtWsDxlKgYKUt2YdZuDPizKPuKA=
    branches:
    - master
    - ".*"
script:
- "./gradlew sonarqube"
after_success:
- mvn clean test jacoco:report coveralls:jacoco

# Set version to tag for release
before_deploy:
  - mvn versions:set -DnewVersion=$TRAVIS_TAG
  - mvn package -Dmaven.test.skip=true
  -
# Deploy with gradle task
deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: BBJ2qN2gD20uE2L1tKTKJaYa6yAFgOagM93edhBVaYG/zEnIBEYMOwi8W1/UlrTYOtHk5Iu9zznQLWaRZDdlsVuNPdWrh6BXGZIgRzN1PxGRwnL1Yjqjf5Zn63p5SjU0HnsIPTv8DgrG8vqcj6jX15paaZBbo0vXDwumpdH6UgPrvo349m0Z+sNSbr9Aw4GDhLCqoOLUBEiHaHvgngjTYTyQtNwDI4JQBpdXdn4mAeQWVsmr4ucXh87hnWlRBhTLnMy9X8f0BnWgy9rYh6S9nja90u1Y+q96+eB71r7uBC/rmePTKU2gikAkqNp5MOqoY1bH7RjWu2+1udl0NpAc3HpCSGadL2g3FbAUF35Th9gVpiCivEZl7+g2ynLo8jEURVA/39ODonbj/my1nU7ntXGj3nxrLhii2nngLy3blFkwdjBkyq60KgLU9xV3ROwCEPkfJk3VglClB0lj9fE2gKpz6Yft4sTWEa9CJT6jtTjAl8eGcxOO7h7ltZfSDeZRX9I4eJvMrwaWhIzliCck2+a34boWeTlaTa/L5AVsfmIxxIWtIrS2j7HvtsW5JbJ2uOKNs1jwWxo9r4PvlIXoLR/5RBlC9OrsIvAHPFAzS9vV1D4HQiq/BtPaTJqzA0NT+MsbBTyanWLh4pGyjtWsDxlKgYKUt2YdZuDPizKPuKA=
